# Build the React/JavaScript front-end
build-front-end-job:
  stage: build
  image: node:lts-bullseye
  variables:
    # If either of these variables is defined in the GitLab
    # CI/CD variables, that value will override the value here.
    PUBLIC_URL: ${PUBLIC_URL}
    REACT_APP_API_HOST: ${REACT_APP_API_HOST}
  script:
    - cd ghi
    - npm install
    - npm run build
    - cp build/index.html build/404.html
  artifacts:
    paths:
      - ghi/build/

# Deploy the React/JavaScript front-end to GitLab pages
pages:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  dependencies:
    - build-front-end-job
  needs:
    - build-front-end-job
  script:
    - mv ghi/build/ public
  artifacts:
    paths:
      - public
